export * as ThreeKit from './engine.js';
export { Viewport3D } from './three.js';
export { SvgOrbit } from './svg-orbit.js';
export type { SvgOrbitPose } from './svg-orbit.js';
export type { Shot3D, ShotTransition3D } from './shots.js';
export type { LabelOptions, LabelInsets, Face } from './labels.js';
export { arrangeTensorRows, deliverTensorCells, calculateTensorColumns } from './tensor-motion.js';
export type { TensorCell, TensorHandle, Point3 } from './tensor-motion.js';
export { readableFrame, geometryFrameAnchors } from './framing.js';
export type { FrameAnchor, ReadableFrame } from './framing.js';
